/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 scene.gltf --transform
Author: Quiznos323 (https://sketchfab.com/quiznos323)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/imperial-at-at-walker-old-version-star-wars-60dad6a198fc4351990c1112df46e180
Title: Imperial AT-AT Walker (old version) - Star Wars
*/

import React, { useRef, useEffect, useState } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

const AtAtModel = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    ".//atat.glb"
  );
  const { actions } = useAnimations(animations, group);
  const [mixer] = useState(() => new THREE.AnimationMixer(nodes._rootJoint));

  useEffect(() => {
    animations.forEach((animation) => {
      mixer.clipAction(animation).play();
    });

    return () => {
      mixer.stopAllAction();
    };
  }, [animations, mixer]);

  useFrame((_, delta) => {
    mixer.update(delta);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive
          object={nodes._rootJoint}
          scale={props.smallView ? 0.1 : 0.12}
          position={props.smallView ? [0, -1.4, 0] : [0, -2, 0]}
          rotation={[-1.6, 0, 0]}
        />
        <skinnedMesh
          name="Object_123"
          geometry={nodes.Object_123.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_123.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_125"
          geometry={nodes.Object_125.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_125.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_127"
          geometry={nodes.Object_127.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_127.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_129"
          geometry={nodes.Object_129.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_129.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_131"
          geometry={nodes.Object_131.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_131.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_133"
          geometry={nodes.Object_133.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_133.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_135"
          geometry={nodes.Object_135.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_135.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_137"
          geometry={nodes.Object_137.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_137.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_139"
          geometry={nodes.Object_139.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_139.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_141"
          geometry={nodes.Object_141.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_141.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_143"
          geometry={nodes.Object_143.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_143.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_145"
          geometry={nodes.Object_145.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_145.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_147"
          geometry={nodes.Object_147.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_147.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_149"
          geometry={nodes.Object_149.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_149.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_151"
          geometry={nodes.Object_151.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_151.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_153"
          geometry={nodes.Object_153.geometry}
          material={materials.Main_Body_Grey}
          skeleton={nodes.Object_153.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("./atat.glb");

export default AtAtModel;
