/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 scene.gltf --transform
Author: StarWars-Universe (https://sketchfab.com/SWU)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/bb8-animated-15db7644c5b645f195f4d2dc0c5154ec
Title: BB8 (Animated)
*/

import React, { useRef, useState, useEffect } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import * as THREE from 'three';

const BB8Model = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/bb8/bb8.glb');
  const { actions } = useAnimations(animations, group);

  const [mixer] = useState(() => new THREE.AnimationMixer(null));
  const [clock] = useState(() => new THREE.Clock());

  useEffect(() => {
    const newMixer = new THREE.AnimationMixer(group.current);

    animations.forEach((animation) => {
      const action = newMixer.clipAction(animation);
      action.play();
    });

    return () => {
      newMixer.stopAllAction();
    };
  }, [animations]);

  useFrame(() => {
    const delta = clock.getDelta();
    mixer.update(delta);
  });

  useEffect(() => {
    if (actions && actions.Animation) {
      actions.Animation.setEffectiveWeight(1);
      actions.Animation.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="BB8Center_NeutralPose"
          position={[0, -1, 0]}
          scale={props.smallView ? 0.025 : 0.015}
        >
          <group name="BB8Center">
            <group name="BB8BB8_Body">
              <mesh
                name="BB8BB8_Body_Scene_Material_0"
                geometry={nodes.BB8BB8_Body_Scene_Material_0.geometry}
                material={materials.Scene_Material}
              />
            </group>
            <group name="BB8Hatch_Door">
              <mesh
                name="BB8Hatch_Door_Scene_Material_0"
                geometry={nodes.BB8Hatch_Door_Scene_Material_0.geometry}
                material={materials.Scene_Material}
              />
            </group>
          </group>
        </group>
        <group
          name="BB8Center_Head_NeutralPose"
          position={[0, -1, 0]}
          scale={props.smallView ? 0.025 : 0.015}
        >
          <group name="BB8Center_Head">
            <group name="BB8Antena">
              <mesh
                name="BB8Antena_Scene_Material1_0"
                geometry={nodes.BB8Antena_Scene_Material1_0.geometry}
                material={materials.Scene_Material1}
              />
            </group>
            <group name="BB8BB8_Head">
              <mesh
                name="BB8BB8_Head_Scene_Material1_0"
                geometry={nodes.BB8BB8_Head_Scene_Material1_0.geometry}
                material={materials.Scene_Material1}
              />
            </group>
            <group name="BB8Eye">
              <mesh
                name="BB8Eye_Eye_0"
                geometry={nodes.BB8Eye_Eye_0.geometry}
                material={materials.material}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/bb8/bb8.glb');

export default BB8Model;
